### ISSUE TITLE
Contact type validation

### ISSUE THREAD

**Issue by banstola** [Sage/sageone_api_php_sample#11]
I am trying to POST following json using the sample library and using the sample post json

```
{
  "contact": {
    "contact_type_ids": [
      "CUSTOMER"
    ],
    "name": "ACME plc"
   }
}
```

Then I get following error. What is the correct way to put the contact_type_ids so that it passes validation? I using the sample JSON from this link .

https://developer.columbus.sage.com/docs#/uki/sageone/accounts/v3/contacts_contact

According to documentation ```contact_type_ids``` is ```array(string())``` .

```json
{
        "$severity": "error",
        "$dataCode": "Validation",
        "$message": "contact[contact_type_ids] is invalid",
        "$source": "contact[contact_type_ids]"
    }

```

**Comment by cpetschnig** [comment]
I have just double-checked your request. This is exactly how you are supposed to create a new customer. Can you please check your code to ensure this is really what you are sending? Thanks.

**Comment by banstola** [comment]
Hi, I am just using the sample php code that SageOne has provided? Did you use the same sample library to verify ? 


```php

  $token = "my_token";//$_POST['post_access_token'];
  $sageone_guid = "my_guid";//$_POST['post_resource_owner_id'];
  $url ="https://api.columbus.sage.com/uki/sageone/accounts/v3/contacts";



    $data= <<<STR
{
  "contact": {
    "contact_type_ids": [
      "CUSTOMER"
    ],
    "name": "ACME plc"
  }
}
STR;
  $post_data = utf8_encode($data);

  /* get the body params as an array of key => value pairs */
  $params = json_decode($post_data, true);

  /* generate the request signature */
  $signature_object = new SageoneSigner("post", $url, $params, $nonce, $signing_secret, $token, $sageone_guid);
  $signature = $signature_object->signature();

  /* add the token, signature and nonce to the request header */
  array_push($header, "Authorization: Bearer " . $token, "X-Signature: " . $signature, "X-Nonce: " . $nonce, "X-Site: " . $sageone_guid);

  $response = $sageone_client->postData($url, $params, $header);

```


there also exists ```contact_type``` **CUSTOMER** and **VENDOR** .

**Comment by banstola** [comment]
Any update on this?

**Comment by buzz1710** [comment]
Hi. Can you confirm that you are using the v3 branch for this?

**Comment by banstola** [comment]
Hi, I am just modifying
 https://github.com/Sage/sageone_api_php_sample/blob/v3/sageone_response.php file as you can see in the code snippet I have posted above.

**Comment by buzz1710** [comment]
I've just tested this using the v3 branch and it's posting that JSON ok.

I see you have just closed this issue anyway - just repoen this or raise another issue if you have any further problems.

If you did manage to resolve this, I'd be interested to know where you were going wrong - we need to improve our docs on these samples and also in general so any feedback is welcome.

**Comment by banstola** [comment]
Hi, it was again my fault here while I was modifying the client file for in house use. But I would suggest  so that we could have a wrapper. So what one could do it create new instance of Sage One with the creds and  be able to make api requests.

```
$sageOne= new SageOne($creds);
$sageOne->get->contacts($query);
```
I think I will make pull request at some point. You guys have been really helpful. Thank you very much.
