### ISSUE TITLE
Updating invoice status

### ISSUE THREAD

**Issue by flashnodeuser** [Sage/sageone_api_php_sample#12]
What is the correct endpoint for updating invoice status? Is there documentation on it? Currently all the invoices are by default Unpaid.

**Comment by cpetschnig** [comment]
Because of the accounting entries, that are created in the background, invoices can only be created as unpaid. You then need to record a payment to change the status. There are various forms of payments:

* [contact payments](https://developer.columbus.sage.com/docs#/us/sageone/accounts/v3/contact_payments_contact_payment)
* [contact allocations](https://developer.columbus.sage.com/docs#/us/sageone/accounts/v3/contact_allocations) which can also been seen as kind of payments

There are also [other payments](https://developer.columbus.sage.com/docs#/us/sageone/accounts/v3/other_payments), but they are not connected to invoices.

**Comment by flashnodeuser** [comment]
I have pushed the contact payment and its recorded in the bank. Then I PUT the sales_invoice with status_id =>"PAID" in SageOne but the status is still unpaid.

**Comment by cpetschnig** [comment]
The status is not directly writeable, it only changes through payments. When you GET the invoice again, do you see the payment? Did you pass the transaction_id of the invoice to the payment?

**Comment by flashnodeuser** [comment]
array:7 [▼
  "transaction_type_id" => "CUSTOMER_RECEIPT"
  "date" => "2017-04-07"
  "contact_id" => "contact_id"
  "total_amount" => "12.0"
  "reference" => "3005"
  "bank_account_id" => "bank_account_id"
  "transaction_id" => "transaction_id" 
]

transaction_id taken from invoice -> transaction->id


Yet it is unpaid at Sage One but this sum has been registered to the bank

**Comment by cpetschnig** [comment]
Sorry, I was wrong. It's not the `transaction_id` that you should use, but the `artefact_id`, as seen in this example:

```
{
  "contact_payment": {
    "transaction_type_id": "VENDOR_PAYMENT",
    "contact_id": "0b47c0ba60a88bd00b199158272sGBP",
    "bank_account_id": "0c47c0ba0c88bd00b199158272d678",
    "date": "2016-01-01",
    "total_amount": 240,
    "reference": "VPAY001",
    "exchange_rate": 0.5,
    "base_currency_currency_charge": 2.5,
    "allocated_artefacts": [
      {
        "artefact_id": "0c47c0pi0188bd00b199158272d678",
        "amount": 240,
        "discount": 0
      }
    ]
  }
}
```
from https://developer.columbus.sage.com/docs#/uki/sageone/accounts/v3/contact_payments_contact_payment

**Comment by flashnodeuser** [comment]
````
"allocated_artefacts": [
      {
        "artefact_id": "0c47c0pi0188bd00b199158272d678",
        "amount": 240,
        "discount": 0
      }

`````

Do artefact_id should be transaction-> id ?

**Comment by cpetschnig** [comment]
No, that's the sales invoice or purchase invoice id.

**Comment by flashnodeuser** [comment]
Too many accounting lessons for a developer. Thank you!

**Comment by cpetschnig** [comment]
Glad I could help. I already recorded an internal ticket to improve the documentation in this area. Cheers!

**Comment by flashnodeuser** [comment]
Is there a way to register the payment gateway while registering the payment? Because using the UI it is possible to select a payment gateway while recording payment

**Comment by adamgeorgeson** [comment]
Hey @flashnode, could you clarify the field in the UI?

Is it the `method` field when making a payment as shown in the screenshots below? If so, we do not currently expose this via the API, and this will default to the `Default Transaction Method` associated with the bank account record.

![screen shot 2017-04-18 at 09 19 37](https://cloud.githubusercontent.com/assets/2270985/25121259/055313dc-2419-11e7-9bc0-4d408df9722b.png)
![screen shot 2017-04-18 at 09 25 35](https://cloud.githubusercontent.com/assets/2270985/25121260/0554b778-2419-11e7-9424-21944ca60b1e.png)

Cheers,
Adam.

**Comment by flashnodeuser** [comment]
The screenshot is correct and i have got my answer that you do not expose them right now.
