### ISSUE TITLE
Apply discount to invoice in bulk

### ISSUE THREAD

**Issue by banstola** [Sage/sageone_api_php_sample#14]
Is there a possibility apply discount to invoice in bulk like we add shipping_cost? Right now the discount is applied to individual product.

**Comment by cpetschnig** [comment]
No, discount must be applied to each single line item. It behaves the same way as the web application/UI.

**Comment by banstola** [comment]
This might be a problem because if there are 3 line items being pushed using API and if there is only single discount amount then there is no way to separate this single amount among 3 line items. Thank you for your quick reply.
