### ISSUE TITLE
Profit analysis report not showing correct information

### ISSUE THREAD

**Issue by banstola** [Sage/sageone_api_php_sample#18]
Hello team,

Our system pushes sales invoices to sage one correctly. Correct product is assigned to inovice_lines and it also appears in Sage One and the client has the matching product code in the origin system as well as in Sage one and same price. Yet the profit analysis is incorrect and does not show the actual cost price of the item in question? I had written an email to your support team and they told me that if we assign correct product_id while creating sales invoice then the profit analysis report are correct yet it has not been the case and cost price is 0 for product in profit analysis report.

One problem could be sometime same product is pushed and assigned VAT 20% and while other time the same product can have VAT 0% (outside EU). Waiting for your reply.

Thank you!

**Comment by cpetschnig** [comment]
We have recorded this in our internal ticket system as API-1735.

**Comment by banstola** [comment]
So is it a bug ? If it is a bug it would be nice to know when it will be fixed or if we are doing something wrong then would love to hear how we could do it correctly.
