### ISSUE TITLE
Rounding up prices 

### ISSUE THREAD

**Issue by banstola** [Sage/sageone_api_php_sample#19]
When pushing invoices to Sage One using API . ```unit_price```  and ```tax_amount``` are rounded up if having more than 2 digits after decimal point thus the total price increases by 1 cent. This is inconvenient.  For example uni price 41.625 and tax 8.325 should be 49.95 but it is 49.96 in the total invoice in Sage One.

**Comment by cpetschnig** [comment]
This has already been subject of long discussions in our team. In fact, both ways to handle rounding can be seen as correct: rounding before or after the addition. On the printed invoices, where all numbers have two digits, we decided to round before the addition. This is more natural for the person reading the invoice.

**Comment by banstola** [comment]
It might be natural but it has caused this issue of increasing 1 pence in every new order . How should we solve this or what could we do in our end? Some systems provide these kinds of numbers and even if we manipulate the data before pushing to Sage One ... it is unlikely that we will be able come up with a generic solution that can cover all the round up issues. Could you not leave this up to the customer to decide what is best suited for them?

**Comment by cpetschnig** [comment]
Unfortunately, such a change cannot be decided not implemented by the Sage One API team. I have forwarded this to our product management, but I can make no promises if or when this will be implemented.

**Comment by banstola** [comment]
That's very unfortunate. I still do not understand why you would round up or down monetary values pushed to the system. This is very inconsistent. Why does it matter if there is 1.564 as price for an item in a invoice if that is what the user wants ? Is there any way we could override this so that the final value is still the correct sum total ?

**Comment by banstola** [comment]
Any way to override this so we get the total sum correct ?
