### ISSUE TITLE
How can we query (get) particular contact without id i mean by name of type like vendor or customer?

### ISSUE THREAD

**Issue by corientdev** [Sage/sageone_api_php_sample#21]
How can we query (get) particular contact without id i mean by name of type like vendor or customer?

**Comment by cpetschnig** [comment]
You can do a `https://api.columbus.sage.com/global/sageone/accounts/v3/contacts?search=contact+name` which searches contact name, company name or reference. Also, there is `.../contacts?email=yourname@example.com`. To only get customers or vendors, do `.../contacts?contact_type_id=CUSTOMER` or `.../contacts?contact_type_id=VENDOR`.
