### ISSUE TITLE
Token return failure

### ISSUE THREAD

**Issue by alsoNuBe** [Sage/sageone_api_php_sample#24]
Hi - I am using your source code pretty much exactly as in the repository.
However, in authentication the SageoneClient->getToken() function seems to not return a token and I am not sure why. Everything seems to work up until the $result = file_get_contents() line.

Could you please suggest some way to debug? I show the function below with my comments:

  private function getToken($params) {
    $url = $this->token_endpoint;
    $options = array('http' => array('header'  => "Content-type: application/x-www-form-urlencoded\r\n",
                                     'method'  => 'POST',
                                     'content' => http_build_query($params)));
    $context  = stream_context_create($options); // var_dump($context) shows resource(4) of type (stream-context)
    $result = file_get_contents($url, false, $context);    // echo $url shows http://app.sageone.com/oauth2/token
    var_dump($result); // returns bool(FALSE) - not sure why I am not getting a token?_
    if ($result === FALSE) { /* Handle error */ }
    return $result;
  }

Please let me know if additional info is needed from me.

**Comment by alsoNuBe** [comment]
I managed to solve the connection problem by using CURL instead of stream_context_create and file_get_contents, so the sample app is now running. The syntax for queries is still something that I do not find easy to apply, e.g.:
accounts/v3/sales_invoices?page=# works, but it is not clear how to use search, etc. How can I see examples of how this is used, please?

**Comment by alsoNuBe** [comment]
I have used CURL instead of file_get_contents and this is working; also making progress with query syntax thanks to the Sage API site.

**Comment by NeonHorizon** [comment]
Can you share your CURL code?
I have tried implementing it in CURL and I'm getting {"error":"invalid_grant"}.
It seems all three of these issues are connected in some way:
https://github.com/Sage/sageone_api_php_sample/issues/38 https://github.com/Sage/sageone_api_php_sample/issues/23

**Comment by NeonHorizon** [comment]
We have resolved our issue but it may not be the same as the problem you have here, we did not have to resort to using CURL other than to get the actual error message, it turned out the problem was elsewhere.
