### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by teufelmartin** [Sage/sageone_api_php_sample#29]
Is there a document available which give more informations about error messages?

`{
  "purchase_invoice": {
    "contact_id": "e9578549eaec11e7b587065b8ec10ed1",
    "date": "2018-01-01",
    "due_date": "2018-02-01",
    "reference": "paypal zb oder oder id",
    "invoice_lines": [
      {
        "product_id": "4568d9e0eaed11e7b587065b8ec10ed1",
        "description": "Line 1",
        "ledger_account_id": "541de418eb0011e7b587065b8ec10ed1",
        "quantity": 1,
        "unit_price": 69.90,
        "tax_amount": 0
      }
    ]
  }
}`

I got this error:
`[
    {
        "$severity": "error",
        "$dataCode": "RecordInvalid",
        "$message": "Couldn't find Supplier.",
        "$source": ""
    }
]`

I work with DE API of sage one accounting.

https://developer.columbus.sage.com/docs#/de/sageone/accounts/v3/purchase_invoices_purchase_invoice_invoice_lines redirects to starting page

**Comment by timlapluie** [comment]
Hi @teufelmartin,
The error you are seeing here means that the `contact_id` you provided in the payload is invalid for the purchase invoice you are trying to create.
The error message unfortunately misses the `$source` attribute. 
Please make sure that the given `contact_id` is a valid supplier (not customer) in Sage One.
