### ISSUE TITLE
Why does this error occurs?

### ISSUE THREAD

**Issue by flashnodeuser** [Sage/sageone_api_php_sample#32]
Hi, 
We have been randomly getting following error when creating new invoice. Where may we find document about this error or when does this error is raised?
```{"error_message":"[{\"$severity\":\"error\",\"$dataCode\":\"RecordNotFound\",\"$message\":\"Couldn't find record.\",\"$source\":\"\"}]"}```

**Comment by cpetschnig** [comment]
Hi,

unfortunately the error message is not that helpful, apologies for that.

Can you please verify that the `contact_id`, `ledger_account_id`, `product_id` in your post data are all valid? Also, please double-check that the referenced contact for a sales invoice is a customer, or a vendor/supplier for a purchase invoice. The ledger account must also be valid and show up in `GET /ledger_accounts?visible_in=sales` for sales invoices. For a purchase invoices, use `visible_id=expenses`.

Does this help?
