### ISSUE TITLE
getting ["error"]=> string(13) "invalid_grant" when I am trying to getAccessToken

### ISSUE THREAD

**Issue by davidherlopgt** [Sage/sageone_api_php_sample#35]
Hi
I am trying to get the access token but the response is invalid_grant, I do receive the authorization code, I read the documentation and I am almost sure that I do everything like is describe
Could some one help me please
array(2) { ["url"]=> string(34) "https://oauth.na.sageone.com/token" ["data"]=> string(161) "client_id=f5xxxxxxxxxxxxxxxeef&client_secret=5axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxe0f&code=0e7b41a9b9f1205cc29a9dcd059da3db274b301c&grant_type=authorization_code" } object(stdClass)#5 (1) { ["error"]=> string(13) "invalid_grant" }

**Comment by cpetschnig** [comment]
Hi David, you have only 60 seconds to exchange the token after authorization and callback. Are you within this timespan?

**Comment by davidherlopgt** [comment]
The call to the accesstoken is done automatically when receiving the code, it does not take more than a second

**Comment by davidherlopgt** [comment]
It's work, my mistake was that I had the redirect_uri different, thanks for answering
