### ISSUE TITLE
getAccessToken error 400

### ISSUE THREAD

**Issue by Biscuri** [Sage/sageone_api_php_sample#38]
When I try to get the access token after getting my code, it gives me the exception:

file_get_contents(https://api.sageone.com/oauth2/token/): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request

Where file_get_contents is the line 123 of sageone_client.php file, inside the getToken method.

The post is sent to: https://api.sageone.com/oauth2/token/

With these params:

`"http" => array:3 [`
`      "header" => "Content-type: application/x-www-form-urlencoded\r\n"`
`      "method" => "POST"`
`      "content" => "client_id=CLIENT_ID&client_secret=CLIENT_SECRET&code=MY_CODE&grant_type=authorization_code&redirect_uri=MY_URI"`
`]`

Where CLIENT_ID, CLIENT_SECRET and MY_URI are respectively copied from the application params, and MY_CODE is the code param of the callback.

Why was it working and suddenly giving me error 400 again? I didn't change none of the application fields, nor any Sage account settings.

**Comment by NeonHorizon** [comment]
We had a version of this code implemented on production servers running different versions of Linux and PHP and it suddenly started failing with 400 errors despite nothing having changed our side.

After re-implementing getToken in curl we have identified that the error Sage are giving is {"error":"invalid_grant"} which link it to this issue here:
https://github.com/Sage/sageone_api_php_sample/issues/23

I am currently in conversation with Sage support with regards to this.

**Comment by NeonHorizon** [comment]
Looks like its also linked to this issue...
https://github.com/Sage/sageone_api_php_sample/issues/24

**Comment by NeonHorizon** [comment]
OK we have resolved our issue with this but it may not match yours.
The first thing I would do is try the request on the command line using curl to find out what the error actually is. I will speak more on our specific problem in here https://github.com/Sage/sageone_api_php_sample/issues/23

**Comment by plantryan** [comment]
I was getting the same error message from file_get_contents. However on closer inspection found that the token endpoint URL in sageone_constants.php was incorrect...

$uki_token_endpoint = 'http://app.sageone.com/oauth2/token';

Should be:

$uki_token_endpoint = 'https://api.sageone.com/oauth2/token';

Hope this helps.

**Comment by NucsuM** [comment]
If somebody of you have questions about the Sage Business Cloud Accounting API or want to report problems, then the [accounting api section of sagecity.com](https://www.sagecity.com/developer/accounting-api/) is the perfect place.
