### ISSUE TITLE
Wrong endpoint for UK token

### ISSUE THREAD

**Issue by mattimatti** [Sage/sageone_api_php_sample#42]
Hello, 
In the provided code V3 there is a wrong endpoint for token exchange

![sageone_api_php_sample_sageone_constants_php_at_v3_·_Sage_sageone_api_php_sample](https://user-images.githubusercontent.com/837528/56224603-27180500-6070-11e9-93b1-98f1a5ec39ee.png)

The correct url is noted in documentation.

![Sage_APIs](https://user-images.githubusercontent.com/837528/56224653-3d25c580-6070-11e9-93fa-274e59bd4be2.png)

**Comment by mattimatti** [comment]
This is possibly the reason for the failure in issue #9

**Comment by cpetschnig** [comment]
Thank you, this will be fixed with https://github.com/Sage/sageone_api_php_sample/pull/47. Strange, I wonder why I pushed this in.

**Comment by NucsuM** [comment]
If you have questions about the Sage Business Cloud Accounting API or want to report problems, then the [accounting api section of sagecity.com](https://www.sagecity.com/developer/accounting-api/) is the perfect place.
