### ISSUE TITLE
Creating contact API docs have no reference to contact_type_form_proxy_id

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [Sage/sageone_api_php_sample#5]
Hi,

Started integrating our application and found the following error on posting a new contact to the en/v1 api:

``` php
object(stdClass)#207 (1) {
  ["$diagnoses"]=>
  array(2) {
    [0]=>
    object(stdClass)#205 (4) {
      ["$severity"]=>
      string(5) "error"
      ["$dataCode"]=>
      string(15) "ValidationError"
      ["$message"]=>
      string(40) "Must specify either customer or supplier"
      ["$source"]=>
      string(4) "base"
    }
    [1]=>
    object(stdClass)#196 (4) {
      ["$severity"]=>
      string(5) "error"
      ["$dataCode"]=>
      string(15) "ValidationError"
      ["$message"]=>
      string(23) "This field is required."
      ["$source"]=>
      string(26) "contact_type_form_proxy_id"
    }
  }
}
```

Any help would be very much appreciated.

**Comment by Caffe1neAdd1ct** [comment]
Please ignore this one! Issue was found between seat and keyboard :+1:

**Comment by LucasRodriguez0302** [comment]
I know this is almost 5 years old but we are having the same issue... do you happen to remember what was happening on your end @Caffe1neAdd1ct ?

**Comment by cpetschnig** [comment]
Hi Lucas, can you give more details please? This issue describes a request to the v1 API, which has been turned off last year. The current API version is documented here: https://developer.sage.com/accounting/

**Comment by LucasRodriguez0302** [comment]
Hi @cpetschnig. Yes, we are using the latest version and we are getting the exact same error, tho we can't find any documentation related to `contact_type_form_proxy_id`

**Comment by cpetschnig** [comment]
Can you please give me a sample of your payload? `contact_type_form_proxy_id` is an internal attribute that unfortunately once surfaced in the API but now shouldn't anymore.

This is an example for the smallest possible payload to create a contact:

    {
      "contact": {
        "name": "Harriet Tubman",
        "contact_type_ids": [
          "CUSTOMER"
        ]
      }
    }

**Comment by LucasRodriguez0302** [comment]
We have captured the error with one of our customer's account but we didn't capture the payload, so we are trying to understand or pinpoint what could've triggered it... We will try to capture the payload in case it happens again
