### ISSUE TITLE
Compatability with Portugal

### ISSUE THREAD

**Issue by ideiasf** [Sage/sageone_api_php_sample#56]
Hello
How compatible is this sample with Portuguese SAGE ONE?

I'm trying to authorize my account with this sample, but I only get all flags except Portugal.

**Comment by cpetschnig** [comment]
The Portuguese Sage One application runs on a different code base and does not have the current API version v3.1. Without any warranty, I'd kindly ask you to rewind back to a commit before 2018 or try the `v1_v2` branch of this repo.
