### ISSUE TITLE
AccessTokenStore->save() doesn't update internal properties

### ISSUE THREAD

**Issue by AlanBell** [Sage/sageone_api_php_sample#57]
If you call ApiClient->renewAccessToken() this gets a new token and calls storeAccessToken which in turn calls AccessTokenStore->save() which writes the data to the yaml file. This does not update the access token in the access store object so the next call to the api fails with invalid_grant as it is still using the old access token.

You need to call ApiClient->accessTokenStore->load() before using the api after renewing. I can't see any reason why you would want to store stuff in the yaml file without loading it back again.

**Comment by NucsuM** [comment]
Thanks @AlanBell for your investigation. The next time, when we update this application we will have a look at this problem.

If you have questions about the Sage Business Cloud Accounting API or want to report problems, then the [accounting api section of sagecity.com](https://www.sagecity.com/developer/accounting-api/) is the perfect place.
