### ISSUE TITLE
access_token.yml

### ISSUE THREAD

**Issue by sumitwaghmare** [Sage/sageone_api_php_sample#62]
can you help me with template of this file? i'm not sure on how to configure this file.
Please help!

**Comment by NucsuM** [comment]
Hello @sumitwaghmare will be generated by the application and it contains the `access_token`, `refresh_token` and their `expiring_times` as unix time . You dont need to edit it (but you could). The only file that you need to edit, is the `client_application.yml`. Just fill it with the credentials that you created in the "Your Apps" section of the [developer serfservice](https://developerselfservice.sageone.com/).

If you have questions about the Sage Business Cloud Accounting API or want to report problems, then the [accounting api section of sagecity.com](https://www.sagecity.com/developer/accounting-api/) is the perfect place.
