### ISSUE TITLE
$oauthClient typo..

### ISSUE THREAD

**Issue by mattimatti** [Sage/sageone_api_php_sample#63]
https://github.com/Sage/sageone_api_php_sample/blob/ac6d4f908972dfd12f180799b11fa234ac90dd66/lib/api_client.php#L60

**Comment by cpetschnig** [comment]
Apologies, I just can't see the typo. Can you please give more info? Thanks!

**Comment by rpsimao** [comment]
it should be ``` $this->oauthClient``` not ``` $this->$oauthClient ```
