### ISSUE TITLE
Authorization failed when using V3 SageOne Signer

### ISSUE THREAD

**Issue by banstola** [Sage/sageone_api_php_sample#9]
The v2 sample and signer works but when using this new API v3 Signer I get authorization failed. 
```json
[
    {
        "$severity": "error",
        "$dataCode": "AuthorizationFailure",
        "$message": "Access denied.",
        "$source": ""
    }
]
```

--------------------------------------------------------------

```php
  $client_id = 'MY_APP_ID';
  $client_secret = 'MY_SECRET';
  $signing_secret = 'MY_S_SECRET';
  $apim_subscription_key = 'SUBSCRIPTION_ID';
  $callback_url = 'MY_CALLBACK_URL';
  $scope = 'full_access';
  $auth_endpoint = 'http://www.sageone.com/oauth2/auth';
  $us_token_endpoint = 'http://mysageone.na.sageone.com/oauth2/token';
  $ca_token_endpoint = 'http://mysageone.ca.sageone.com/oauth2/token';
  $uki_token_endpoint = 'http://app.sageone.com/oauth2/token';
  $us_base_endpoint = 'https://api.columbus.sage.com/us/sageone/';
  $ca_base_endpoint = 'https://api.columbus.sage.com/ca/sageone/';
  $uki_base_endpoint = 'https://api.columbus.sage.com/uki/sageone/';

```

-----------------------

I used 

http://localhost:8080/sageone_response.php?get_endpoint=accounts%2Fv3%2Fcontacts&get_access_token=MY_ACCESS_TOKEN&get_resource_owner_id=MY_RESOURCE_ID&country=GB

---------------------------------------------

Above works when using samples for api v2. OFC there is slight change in the get parameters in V2 samples. Has anyone else has this issue? Or have you guys tested this sample SageoneSigner with V3? Or is it too early to migrate to V3 for UK account API  as I read in readme.md that it is still in beta and only available in Canada?

**Comment by cpetschnig** [comment]
This looks like your code is fine, but your user is not the owner of the business. Currently, API usage is restricted to the owner of each business. Can you please check this?

It is definitely not to early to use v3, which is available for UK, US, Canada, France, Germany, Ireland and Spain. The API is fully compatible among these countries (which was not the case with v2).

Yes, we'v made some slight changes in the signature generation. Through this we have increased compatibility/consistency to other Sage APIs.

**Comment by banstola** [comment]
Ok. It is then business owner issue as I am trying to get data from Accounts that have authorized me to access their data. Is there any document where you have put this information?  So when can we expect the API without such restrictions so that third party applications will be able to access data on behalf of business owners?

**Comment by cpetschnig** [comment]
We have had this always in the [v1/v2 documentation](https://developer.sageone.com/docs/en/v1#authentication) ("Note: This can only be authorized by the business owner (the user that created the Sage One subscription)"), but probably haven't enforced it all the time. I thought the v3 docs mention it, too, but it looks like they don't. We will correct this.

In general we intend to lift this restriction, but I can not tell you a timeframe, when we will implement this.

Can you live (for now) with the workaround that the business owners click the 'Allow' button themselves?

**Comment by banstola** [comment]
I think we are talking two different things. Business owner "allow" the authorization. I use the code to exchange the ```refresh_token``` and ```access_token ```.  I use the v3 branch with this ```access token``` , ```resource_owner_id``` obtained along with ```refresh_token``` and ```access_token```. I create a new subscription and use the subscription key to update the file contains application constants. 

Then I browse the following. Then I get unauthorized. 

http://localhost:8080/sageone_response.php?get_endpoint=accounts%2Fv3%2Fcontacts&get_access_token=MY_ACCESS_TOKEN&get_resource_owner_id=MY_RESOURCE_ID&country=GB

I get this error.  

```
[
    {
        "$severity": "error",
        "$dataCode": "AuthorizationFailure",
        "$message": "Access denied.",
        "$source": ""
    }
]

```
But when I use the master branch which is for API V2. I have no problem getting/sending data from/to API.

**Comment by cpetschnig** [comment]
On further investigation, the value you use on `get_resource_owner_id` is not valid. This value is used for the `X-Site` header in the request and was introduced in v3. Please verify that this value is the GUID of the business you are making the request for.

**Comment by banstola** [comment]
Now it makes sense as I was using ```requested_by_id``` . But as suggested in this document https://developer.columbus.sage.com/docs#/uki/sageone/accounts/gs-authentication. I do not get ```resource_owner_id``` instead I have the response as below



```json
{
  "refresh_token": "XXXX",
  "expires_in": 3600,
  "access_token": "XXXXX",
  "scope": "full_access",
  "requested_by_id": "XXXXX",
  "token_type": "Bearer"
}
```

Every request I make to API must provide me resource_owner_id instead I get back ```requested_by_id```

**Comment by banstola** [comment]
Nevermind. I was using wrong api endpoint . It works now. Thank you! You saved my day.

**Comment by rajiv-1990** [comment]
Hello Sir 

I m getting following error. I have used "https://api.columbus.sage.com/uki/sageone/accounts/v3/contacts?email=test@gmail.com"

[
  {
    "$severity": "APIM error",
    "$dataCode": "SubscriptionKeyInvalid",
    "$message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.",
    "$source": "authorization"
  }
]

**Comment by cpetschnig** [comment]
You need to set the `ocp-apim-subscription-key` header in your request. You get the value from https://developer.columbus.sage.com/docs#/uki/sageone/accounts, sign in/register in the top right corner. Use either the primary or secondary key from your subscriptions.

**Comment by futurewebsites** [comment]
@cpetschnig I have followed the above link but cannot find any ocp-apim-subscription-key and when I click my profile there is nothing under subscription details

**Comment by banstola** [comment]
Hi, at https://developer.columbus.sage.com/developer , they are named as Primary Key and Secondary key . You can use either as suggested by @cpetschnig

**Comment by futurewebsites** [comment]
@banstola I had to subscribe to an api first :) but it seems I need owner login to get the resource_owner_id returned is that correct? I have full access on my account but no resource_owner_id is returned

**Comment by plantryan** [comment]
I'm also getting an "AuthorizationFailure" but for a different reason...

```json
[
  {
    "$severity": "error",
    "$dataCode": "AuthorizationFailure",
    "$message": "Access denied. Cannot verify subscription. Please try again later. (MRF)",
    "$source": ""
  }
]
```

I've subscribed to the "Sage One API", and using the primary key as my "apim_subscription_key" to access the /accounts endpoint.

Is this not correct?

**Comment by futurewebsites** [comment]
im getting 
 `[
    {
        "$severity": "APIM error",
        "$dataCode": "HeaderNotFound",
        "$message": "Header X-Site was not found in the request. Access denied.",
        "$source": "check-header[2]"
    }
]`

**Comment by snelbert** [comment]
@cpetschnig can you provide any help on this please?

**Comment by plantryan** [comment]
@cpetschnig can you provide any help on this please?

**Comment by cpetschnig** [comment]
We've made this whole part much easier in the new API version 3.1, where all accounting endpoints are 100% compatible to this v3 version you are referring to. Check out the documentation at https://developer.sage.com/api/accounting/ The new version is in Beta since its release last October, but we will remove the Beta label soon.

**Comment by cpetschnig** [comment]
Unfortunately we haven't yet come across to update the sample applications, but this will follow soon. The new version is also much closer to the OAuth2 specification, which should allow you to use any OAuth2 library with instant success, making the need for this sample app less urgent.
